Создана XML разметка экрана разработчиков
givemesomecoffee/practicum-android-diploma pull request #15
Opened 2023-08-30 17:43 UTC by vaiwork

2023-08-30 17:53 UTC, givemesomecoffee commented on app/src/main/res/layout/fragment_team.xml
>  <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
автоформатирование - Ctrl+Shift+L

2023-08-30 18:01 UTC, Mysteri027 requested changes

2023-08-30 18:56 UTC, Mysteri027 approved these changes

2023-08-30 19:20 UTC, givemesomecoffee commented on app/src/main/res/layout/fragment_team.xml
> +                android:translationY="-0.12sp" />
тут точно это нужно?

2023-08-30 19:25 UTC, vaiwork commented on app/src/main/res/layout/fragment_team.xml
> +                android:translationY="-0.12sp" />
В Figma так, но я подумываю от этого избавиться. Оставлять или убирать?

2023-08-30 19:29 UTC, vaiwork commented on app/src/main/res/layout/fragment_team.xml
> +                android:translationY="-0.12sp" />
В принципе не особо влияет на расположение элемента

2023-08-30 19:32 UTC, givemesomecoffee commented on app/src/main/res/layout/fragment_team.xml
> +                android:translationY="-0.12sp" />
а все вижу откуда, автогенерация кода в фигме. имхо, я бы убрала. На твое усмотрение

2023-08-30 19:34 UTC, givemesomecoffee commented on app/src/main/res/layout/fragment_team.xml
> +            android:layout_marginHorizontal="16dp"
Значения цвета, отступов, размеров текста и строковые константы вынесены в соответствующие файлы ресурсной директории values.
либо доп таску на установку отступов из ресурсов по тз надо сделать либо сразу поправить

2023-08-30 19:47 UTC, vaiwork commented on app/src/main/res/layout/fragment_team.xml
> +            android:layout_marginHorizontal="16dp"
Я сейчас подправлю и коммит новый сделаю

2023-08-30 20:30 UTC, givemesomecoffee approved these changes

2023-08-31 07:28 UTC, Mysteri027 approved these changes

2023-08-31 07:28 UTC, merged